"""add request validation fields

Revision ID: 50f7602a57c9
Revises: 8a974b06ece9
Create Date: 2025-12-01 15:06:24.302651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f7602a57c9'
down_revision: Union[str, None] = '8a974b06ece9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('completion_validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('completion_validated_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['completion_validated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['acknowledged_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'completion_validated_by_user_id')
    op.drop_column('requests', 'completion_validated_at')
    op.drop_column('requests', 'acknowledged_by_user_id')
    op.drop_column('requests', 'acknowledged_at')
    # ### end Alembic commands ###
